&fras "inputs/day03"
# don't box because all lines are the same len
⊜∘≠, @\n
↙ 5

# get the ol' digitmask again
× ≤@9 , ≥@0 .
# get digits
≡(□⊜□) ,,
# uiua is a readable and cool and good language
# all the bullshit out the front is dealing
# with boxing problems
# this results in, for each row of the engine,
# a boxed array for each number string,
# containing that number, repeated a number of
# times equal to the STRING length of the num
≡⍜⊔≡⍜⊔(▽ ⧻: parse.)

# brain horty. bed time
